# Generated by Django 5.1.7 on 2025-07-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('aadhaar_no', models.CharField(default='000000000000', max_length=12)),
                ('emis_no', models.CharField(default='N/A', max_length=20)),
                ('phone_no', models.CharField(default='0000000000', max_length=15)),
            ],
        ),
    ]
